In [2]:
import pandas as pd
import numpy as np
import nltk
import re

In [3]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('corpus')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('vader_lexicon')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/harita_addanki/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/harita_addanki/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading corpus: Package 'corpus' not found in index
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/harita_addanki/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/harita_addanki/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/harita_addanki/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [4]:
data = pd.read_csv('full_reviews.csv')

In [6]:
data.head()

,Unnamed: 0,id,url,business_key,text,rating,time_created,user_id,user_profile,image_url,user_name
0,0,CazdwWa8nBoRSlCaVoFtOg,https://www.yelp.com/biz/hironori-craft-ramen-...,hironori-craft-ramen-irvine-3,"Oh my gosh I was the best VEGAN RAMEN,I've eve...",5,10/19/22 16:50,#NAME?,https://www.yelp.com/user_details?userid=--W5R...,NaN,Kassandra N.
1,1,mLbdnx903STga1sYr05efw,https://www.yelp.com/biz/hironori-craft-ramen-...,hironori-craft-ramen-irvine-3,Wait list and seating is uncoordinated if you ...,3,9/21/22 8:32,2PjR_8Rj6N7L1VFKs0gobA,https://www.yelp.com/user_details?userid=2PjR_...,NaN,Charlie K.
2,2,JlyiMbf_fgwmUzh8oZB_OA,https://www.yelp.com/biz/hironori-craft-ramen-...,hironori-craft-ramen-irvine-3,Ramen worthy of the a Michelin Guide Bib Gourm...,5,11-07-2022 15:06,JUJJ06Y1NCqx0KcSUth4Fw,https://www.yelp.com/user_details?userid=JUJJ0...,https://s3-media3.fl.yelpcdn.com/photo/CvR0YTU...,Daph H.
3,3,xChHOntOyYUjrFmvO9i8JA,https://www.yelp.com/biz/duck-donuts-irvine-ir...,duck-donuts-irvine-irvine,Delicious \nthanks \nFelicia ! Fresh\n customi...,5,10/26/22 18:29,HljSp3aOrQDd5ZyerkWdGg,https://www.yelp.com/user_details?userid=HljSp...,https://s3-media3.fl.yelpcdn.com/photo/jwypNhY...,Stephen F.
4,4,gvwTF69wPVmsFMnuMo3QUw,https://www.yelp.com/biz/duck-donuts-irvine-ir...,duck-donuts-irvine-irvine,BEWARE: This place has so many delicious flavo...,5,10-12-2022 16:27,gMjRybbxoYxNInF4wzjTSA,https://www.yelp.com/user_details?userid=gMjRy...,https://s3-media3.fl.yelpcdn.com/photo/DS0Wx9H...,Jaclyn A.

In [7]:
reviews = pd.DataFrame(data[['text','rating']])

In [8]:
reviews['rating'].value_counts()

5    1756
4     607
3     247
1     221
2     169
Name: rating, dtype: int64

In [9]:
def assign_label(x):
    if(x<3):
        return -1
    elif(x==3):
        return 0
    else:
        return 1

In [10]:
reviews['label'] = reviews['rating'].apply(assign_label)

In [11]:
reviews.head()

                                                text  rating  label
0  Oh my gosh I was the best VEGAN RAMEN,I've eve...       5      1
1  Wait list and seating is uncoordinated if you ...       3      0
2  Ramen worthy of the a Michelin Guide Bib Gourm...       5      1
3  Delicious \nthanks \nFelicia ! Fresh\n customi...       5      1
4  BEWARE: This place has so many delicious flavo...       5      1

In [12]:
reviews['tokens'] = reviews['text'].apply(lambda x: " ".join(x.lower() for x in str(x).split()))

In [13]:
from bs4 import BeautifulSoup
reviews['tokens']=reviews['tokens'].apply(lambda x: BeautifulSoup(x).get_text())
reviews['tokens']=reviews['tokens'].apply(lambda x: re.sub(r"http\S+", "", x))

/Users/harita_addanki/opt/anaconda3/lib/python3.9/site-packages/bs4/__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(

In [14]:
reviews.head()

,text,rating,label,tokens
0,"Oh my gosh I was the best VEGAN RAMEN,I've eve...",5,1,"oh my gosh i was the best vegan ramen,i've eve..."
1,Wait list and seating is uncoordinated if you ...,3,0,wait list and seating is uncoordinated if you ...
2,Ramen worthy of the a Michelin Guide Bib Gourm...,5,1,ramen worthy of the a michelin guide bib gourm...
3,Delicious \nthanks \nFelicia ! Fresh\n customi...,5,1,delicious thanks felicia ! fresh customized do...
4,BEWARE: This place has so many delicious flavo...,5,1,beware: this place has so many delicious flavo...

In [15]:
reviews['rating'].value_counts()

5    1756
4     607
3     247
1     221
2     169
Name: rating, dtype: int64

In [16]:
reviews.head()

,text,rating,label,tokens
0,"Oh my gosh I was the best VEGAN RAMEN,I've eve...",5,1,"oh my gosh i was the best vegan ramen,i've eve..."
1,Wait list and seating is uncoordinated if you ...,3,0,wait list and seating is uncoordinated if you ...
2,Ramen worthy of the a Michelin Guide Bib Gourm...,5,1,ramen worthy of the a michelin guide bib gourm...
3,Delicious \nthanks \nFelicia ! Fresh\n customi...,5,1,delicious thanks felicia ! fresh customized do...
4,BEWARE: This place has so many delicious flavo...,5,1,beware: this place has so many delicious flavo...

In [17]:
reviews['tokens'] = reviews['tokens'].apply(lambda x: " ".join([re.sub('[^A-Za-z]+','', x) for x in nltk.word_tokenize(x)]))

In [18]:
reviews.head()

,text,rating,label,tokens
0,"Oh my gosh I was the best VEGAN RAMEN,I've eve...",5,1,oh my gosh i was the best vegan ramen i ve ev...
1,Wait list and seating is uncoordinated if you ...,3,0,wait list and seating is uncoordinated if you ...
2,Ramen worthy of the a Michelin Guide Bib Gourm...,5,1,ramen worthy of the a michelin guide bib gourm...
3,Delicious \nthanks \nFelicia ! Fresh\n customi...,5,1,delicious thanks felicia fresh customized don...
4,BEWARE: This place has so many delicious flavo...,5,1,beware this place has so many delicious flavo...

In [19]:
reviews['tokens']=reviews['tokens'].apply(lambda x: re.sub(' +', ' ', x))

In [20]:
from nltk.corpus import stopwords
stop = stopwords.words('english') 
reviews['tokens'] = reviews['tokens'].apply(lambda x: " ".join([x for x in x.split() if x not in stop]))

In [21]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
reviews['tokens']=reviews['tokens'].apply(lambda x: " ".join([lemmatizer.lemmatize(w) for w in nltk.word_tokenize(x)]))

In [22]:
reviews.head()

,text,rating,label,tokens
0,"Oh my gosh I was the best VEGAN RAMEN,I've eve...",5,1,oh gosh best vegan ramen ever vegan one boyfri...
1,Wait list and seating is uncoordinated if you ...,3,0,wait list seating uncoordinated party larger p...
2,Ramen worthy of the a Michelin Guide Bib Gourm...,5,1,ramen worthy michelin guide bib gourmand think...
3,Delicious \nthanks \nFelicia ! Fresh\n customi...,5,1,delicious thanks felicia fresh customized donu...
4,BEWARE: This place has so many delicious flavo...,5,1,beware place many delicious flavor difficult m...

In [23]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain, ytest = train_test_split(reviews['tokens'], reviews['label'], test_size=0.20, random_state=101)

In [24]:
xtrain.head()

1488    place pretty much indian panda express right w...
683     love spot located old town tustin parking with...
1199    definitely showoff mallit practically look lik...
579     love place fry best kid obsessed poke bowl fre...
2877    third time ordering birthday cake bakery went ...
Name: tokens, dtype: object

In [25]:
xtest.shape

(600,)

In [26]:
len(reviews['tokens'])

3000

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer= TfidfVectorizer()
tf_xtrain = vectorizer.fit_transform(xtrain)
tf_xtest = vectorizer.transform(xtest)

In [28]:
np.array(tf_xtrain)

array(<2400x5011 sparse matrix of type '<class 'numpy.float64'>'
	with 32724 stored elements in Compressed Sparse Row format>, dtype=object)

In [29]:
vector = pd.DataFrame.sparse.from_spmatrix(tf_xtrain)

In [34]:
vector.shape[1]

5011

In [32]:
vectorizer.get_feature_names()

/Users/harita_addanki/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['aa',
 'ability',
 'able',
 'absolute',
 'absolutely',
 'absurd',
 'abuelita',
 'abundance',
 'abysmal',
 'ac',
 'acai',
 'accept',
 'accepted',
 'accepting',
 'access',
 'accessible',
 'accessoriesmugs',
 'accidentally',
 'accidently',
 'accommodate',
 'accommodated',
 'accommodating',
 'accompaniment',
 'according',
 'accrotrements',
 'accrue',
 'accurate',
 'acknowledged',
 'across',
 'act',
 'activity',
 'actual',
 'actually',
 'ad',
 'adalbertos',
 'add',
 'added',
 'addict',
 'addicted',
 'addicting',
 'addiction',
 'adding',
 'addition',
 'additional',
 'address',
 'adjacent',
 'adjective',
 'adjust',
 'adjusted',
 'admit',
 'adonis',
 'adorable',
 'adore',
 'adult',
 'advance',
 'advantage',
 'advertised',
 'advertisement',
 'advertising',
 'advise',
 'advised',
 'aesthetic',
 'aesthetically',
 'af',
 'affectionately',
 'affordable',
 'aficionado',
 'afternoon',
 'afterwards',
 'agar',
 'agave',
 'age',
 'aged',
 'aggressively',
 'ago',
 'agora',
 'agree',
 'agua',
 'ahboong',
 'ahead',
 'ahhh',
 'ahi',
 'ai',
 'air',
 'airport',
 'airy',
 'aiyu',
 'aka',
 'al',
 'ala',
 'alana',
 'alastair',
 'albeit',
 'alcohol',
 'alexa',
 'alfredo',
 'alguien',
 'aline',
 'allergic',
 'allergy',
 'alley',
 'allie',
 'alll',
 'alllll',
 'allow',
 'allowask',
 'allowed',
 'allows',
 'almond',
 'almost',
 'aloha',
 'alone',
 'along',
 'already',
 'alright',
 'also',
 'alternative',
 'altho',
 'although',
 'alton',
 'always',
 'am',
 'amanda',
 'amaretto',
 'amazed',
 'amazing',
 'amazinggg',
 'amazingly',
 'ambiance',
 'ambience',
 'ambient',
 'amc',
 'america',
 'american',
 'americano',
 'amid',
 'among',
 'amongst',
 'amount',
 'ample',
 'ana',
 'anaheim',
 'anahy',
 'anchor',
 'andor',
 'andrea',
 'andrei',
 'andrew',
 'angel',
 'angeles',
 'angotei',
 'animal',
 'annapoorna',
 'anniversary',
 'annoyed',
 'annoying',
 'annually',
 'another',
 'anqi',
 'answer',
 'answered',
 'anthony',
 'anti',
 'antiauthority',
 'anticipated',
 'antique',
 'antonio',
 'anymore',
 'anyone',
 'anything',
 'anytime',
 'anyway',
 'anywhere',
 'apartment',
 'apetizers',
 'apointment',
 'apology',
 'app',
 'apparently',
 'appealing',
 'appear',
 'appearance',
 'appeared',
 'appetite',
 'appetizer',
 'apple',
 'applerx',
 'appointment',
 'appreciate',
 'appreciated',
 'appreciation',
 'appropriate',
 'appropriately',
 'apps',
 'apt',
 'arab',
 'arabiki',
 'arancini',
 'arcade',
 'area',
 'argentinian',
 'around',
 'arrachera',
 'array',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrow',
 'arroz',
 'art',
 'artesia',
 'arthur',
 'artichoke',
 'artistic',
 'as',
 'asada',
 'asado',
 'asia',
 'asiago',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asparagus',
 'aspect',
 'assed',
 'assembly',
 'assistant',
 'associate',
 'assorted',
 'assortment',
 'assume',
 'assuring',
 'ate',
 'atmosphere',
 'attached',
 'attempt',
 'attempted',
 'attend',
 'attended',
 'attending',
 'attention',
 'attentive',
 'attic',
 'attitude',
 'attracted',
 'attractive',
 'aug',
 'august',
 'aulacrestaurant',
 'auntie',
 'austin',
 'authentic',
 'available',
 'ave',
 'average',
 'averaged',
 'avery',
 'avid',
 'avila',
 'avo',
 'avocado',
 'avoid',
 'awaited',
 'awake',
 'aware',
 'away',
 'awesome',
 'awful',
 'awhile',
 'awkward',
 'axed',
 'ayce',
 'ayutla',
 'baba',
 'babbling',
 'baby',
 'bacchus',
 'bacio',
 'back',
 'backed',
 'background',
 'backup',
 'bacl',
 'bacon',
 'bad',
 'baekjeong',
 'bag',
 'bagel',
 'baguette',
 'bahama',
 'bahn',
 'bahnmi',
 'bailey',
 'bajastyle',
 'baked',
 'bakery',
 'baking',
 'baklava',
 'balance',
 'balanced',
 'ball',
 'ballin',
 'banana',
 'banchan',
 'banchans',
 'bandera',
 'bang',
 'banh',
 'bank',
 'banoffee',
 'banter',
 'banzai',
 'bao',
 'baos',
 'bar',
 'barbecue',
 'barbonzai',
 'barcelona',
 'bardot',
 'bare',
 'barely',
 'bargain',
 'barista',
 'baristas',
 'barolo',
 'barranca',
 'barrestaurant',
 'bartender',
 'base',
 'based',
 'basic',
 'basically',
 'basil',
 'basis',
 'basket',
 'basketball',
 'basmati',
 'bass',
 'bat',
 'bathroom',
 'batter',
 'bay',
 'bazak',
 'bbq',
 'bc',
 'bcd',
 'bday',
 'beach',
 'bean',
 'bear',
 'beard',
 'beat',
 'beaten',
 'beautiful',
 'beautifully',
 'beauty',
 'became',
 'become',
 'becoming',
 'beef',
 'beer',
 'beerbattered',
 'beet',
 'began',
 'begin',
 'beginning',
 'behind',
 'behold',
 'beijing',
 'being',
 'belgian',
 'believe',
 'bell',
 'bellini',
 'belly',
 'beloved',
 'belt',
 'ben',
 'benedict',
 'beneficial',
 'benefit',
 'benihana',
 'bento',
 'bentos',
 'berry',
 'best',
 'bestest',
 'bestie',
 'better',
 'beverage',
 'beware',
 'beyond',
 'bf',
 'bhaji',
 'bib',
 'bibimbop',
 'bicycle',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biking',
 'bill',
 'bing',
 'binging',
 'binh',
 'bird',
 'birria',
 'birthday',
 'biscotti',
 'biscuit',
 'bison',
 'bisque',
 'bistango',
 'bistec',
 'bistro',
 'bit',
 'bite',
 'bitter',
 'black',
 'blade',
 'blame',
 'bland',
 'blast',
 'blasting',
 'blatantly',
 'blaze',
 'blazing',
 'blech',
 'blend',
 'blended',
 'blk',
 'block',
 'blond',
 'blonde',
 'blood',
 'bloody',
 'bloomingdales',
 'blown',
 'blt',
 'blue',
 'blueberry',
 'bluefin',
 'blvd',
 'boat',
 'boba',
 'bobo',
 'bogo',
 'boil',
 'boiled',
 'boiling',
 'bolognese',
 'bomb',
 'bonchon',
 'bonding',
 'bone',
 'bonein',
 'boneless',
 'bongsoo',
 'bonita',
 'bonito',
 'book',
 'booked',
 'bookmark',
 'bookmarked',
 'boomer',
 'booskies',
 'bootea',
 'booth',
 'bos',
 'bosscats',
 'boston',
 'bother',
 'bottle',
 'bottom',
 'bottomless',
 'bought',
 'bougie',
 'boutique',
 'boutiquestyle',
 'bow',
 'bowl',
 'bowling',
 'box',
 'boy',
 'boyfriend',
 'brainer',
 'braise',
 'braised',
 'brand',
 'brandon',
 'bread',
 'breading',
 'break',
 'breakdown',
 'breakfast',
 'breakfastbrunch',
 'breakfastlunch',
 'breathtaking',
 'breeze',
 'breezy',
 'brent',
 'brew',
 'brewed',
 'bridal',
 'bridge',
 'bridget',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brioche',
 'brisk',
 'brisket',
 'bristol',
 'brle',
 'bro',
 'broccoli',
 'broiler',
 'broken',
 'brook',
 'broth',
 'brother',
 'brought',
 'brown',
 'brownie',
 'brunch',
 'bruskis',
 'brussel',
 'bruxie',
 'bruxies',
 'bu',
 'bubble',
 'buck',
 'bucket',
 'bud',
 'buddy',
 'budget',
 'buena',
 'buffalo',
 'buffet',
 'build',
 'building',
 'built',
 'bulgogi',
 'bulky',
 'bullion',
 'bummer',
 'bumped',
 'bumpy',
 'bun',
 'bunch',
 'bundt',
 'bunt',
 'burger',
 'burgerstacos',
 'burn',
 'burner',
 'burning',
 'burnt',
 'burrito',
 'bursting',
 'bus',
 'busier',
 'business',
 'busser',
 'bustling',
 'busy',
 'butter',
 'butternut',
 'butterpecan',
 'buttersalsa',
 'buttery',
 'buy',
 'buying',
 'buzzing',
 'byob',
 'ca',
 'cabbage',
 'cactus',
 'caesar',
 'caf',
 'cafe',
 'caffe',
 'caffeinated',
 'cajun',
 'cake',
 'cakery',
 'cal',
 'calamansi',
 'calamari',
 'cali',
 'california',
 'call',
 'called',
 'calling',
 'calm',
 'calorie',
 'calorific',
 'calzone',
 'camarones',
 'came',
 'camper',
 'campus',
 'cancelled',
 'cancerfree',
 'cancun',
 'cannoli',
 'canopy',
 'cant',
 'canyon',
 'cap',
 'caper',
 'capital',
 'capitalone',
 'caprese',
 'capsule',
 'captured',
 'car',
 'caramel',
 'carb',
 'card',
 'care',
 'carefully',
 'carelessness',
 'caring',
 'carlos',
 'carlsbad',
 'carme',
 'carmen',
 'carne',
 'carnitas',
 'carpet',
 'carried',
 'carrot',
 'carson',
 'cart',
 'carte',
 'carter',
 'carved',
 'carving',
 'case',
 'cash',
 'cashew',
 'cashier',
 'castle',
 'casual',
 'cat',
 'catch',
 'catcher',
 'catching',
 'category',
 'cater',
 'catered',
 'catering',
 'cathered',
 'cauldron',
 'cauliflower',
 'cause',
 'caused',
 'causing',
 'cava',
 'cdm',
 'cece',
 'celebrate',
 'celebrated',
 'celebration',
 'celebratory',
 'cell',
 'cellar',
 'censored',
 'cent',
 'center',
 'centered',
 'central',
 'centro',
 'cerca',
 'cereal',
 'cerritos',
 'certainly',
 'cesar',
 'ceviche',
 'cha',
 'chad',
 'chai',
 'chain',
 'chair',
 'chalaber',
 'challenge',
 'challenging',
 'champagne',
 'champion',
 'chance',
 'chanel',
 'chang',
 'change',
 'changed',
 'changesrotates',
 'changing',
 'chao',
 'chaotic',
 'chapman',
 'char',
 'charcuterie',
 'charge',
 'charged',
 'charging',
 'charming',
 'charsiu',
 'chashu',
 'chat',
 'chaupain',
 'cheap',
 'cheaper',
 'cheat',
 'check',
 'checked',
 'checker',
 'checking',
 'cheese',
 'cheeseburger',
 'cheesecake',
 'cheesesteak',
 'cheesetella',
 'cheesy',
 'cheetos',
 'chef',
 'chefshostbussers',
 'chemicalesque',
 'cherry',
 'cherubic',
 'chestnut',
 'chew',
 'chewy',
 'chi',
 'chia',
 'chiarini',
 'chicago',
 'chick',
 'chicken',
 'chickfila',
 'chicory',
 'chilaquiles',
 'child',
 'childhood',
 'chile',
 'chilean',
 'chili',
 'chill',
 'chilli',
 'chilly',
 'chimichurri',
 'china',
 'chinese',
 'chip',
 'chipotle',
 'chippy',
 'chirashi',
 'chix',
 'chixken',
 'chocolate',
 'chocolatier',
 'choice',
 'choose',
 'choosing',
 'chop',
 'chopped',
 'chorizo',
 'chose',
 'chosen',
 'chow',
 'chowder',
 'chris',
 'christakis',
 'christian',
 'christine',
 'chronic',
 'chugging',
 'chunk',
 'church',
 'churro',
 'chutney',
 'cider',
 'cilantro',
 'cindy',
 'cinnamon',
 'cioppino',
 'citation',
 'citrus',
 'city',
 'claim',
 'clam',
 'clap',
 'claro',
 'class',
 'classic',
 'classroom',
 'classy',
 'claustrophobic',
 'clean',
 'cleaner',
 'cleanest',
 'cleaning',
 'cleanliness',
 'cleanse',
 'clear',
 'clearly',
 'clemente',
 'clever',
 'click',
 'client',
 'climbing',
 'close',
 'closed',
 'closer',
 'closest',
 'closing',
 'clothes',
 'cloud',
 'cloudy',
 'club',
 'clue',
 'co',
 'coach',
 'coached',
 'coast',
 'coat',
 'cobb',
 'cochinita',
 'cocina',
 'cocktail',
 'coconut',
 'code',
 'cody',
 'coffee',
 'coffeeshop',
 'cold',
 'coleslaw',
 'colleague',
 'collection',
 'college',
 'color',
 'combination',
 'combo',
 'come',
 'comedy',
 'comfort',
 'comfortable',
 'comforting',
 'comfy',
 'coming',
 'command',
 'comment',
 'commentingl',
 'commercial',
 'committed',
 'common',
 'communicating',
 'communication',
 'community',
 'como',
 'company',
 'comparable',
 'compare',
 'compared',
 'compelled',
 'competing',
 'competition',
 'complain',
 'complaining',
 'complaint',
 'complement',
 'complete',
 'completely',
 'completes',
 'completion',
 'complex',
 'complicated',
 'complimentary',
 'compromised',
 'con',
 'concept',
 'concern',
 'concert',
 'condiment',
 'condition',
 'cone',
 'confidence',
 'confident',
 'confidently',
 'confirm',
 'confused',
 'confusing',
 'conjures',
 'connection',
 'connie',
 'connoisseur',
 'conquer',
 'consider',
 'considerably',
 'considerate',
 'considering',
 'consist',
 'consistency',
 'consistent',
 'consistently',
 'consisting',
 'constantly',
 'construction',
 'consume',
 'consumer',
 'contact',
 'contacted',
 'contemporary',
 'continue',
 'continued',
 'continues',
 'contra',
 'contract',
 'contrast',
 'control',
 'convenience',
 'convenient',
 'conveniently',
 'converter',
 'conveyor',
 'convinced',
 'convinces',
 'cook',
 'cooked',
 'cookie',
 'cooking',
 'cooky',
 'cool',
 'cooler',
 'coop',
 'coordinating',
 'corkage',
 'corn',
 'corner',
 'coronado',
 'corporate',
 'correct',
 'correctly',
 'cortado',
 'cortina',
 'cost',
 'costa',
 'cotta',
 'couch',
 'could',
 'count',
 'counter',
 'counterpart',
 'countless',
 'country',
 'county',
 'couple',
 'coupon',
 'course',
 'court',
 'courtesy',
 'cousin',
 'cove',
 'cover',
 'covered',
 'covid',
 'coward',
 'coworker',
 'coworkers',
 'cozy',
 'cpk',
 'crab',
 'craft',
 'crafted',
 'craftsman',
 'cramped',
 'crate',
 'crave',
 'craved',
 'craving',
 'crawfish',
 'crazy',
 'cream',
 'creamiest',
 'creamin',
 'creaminess',
 'creamy',
 'create',
 'created',
 'creative',
 'credit',
 'creek',
 'creepy',
 'creme',
 'crepe',
 ...]

In [37]:
d = dict()
column = 0
features = list(vectorizer.get_feature_names())
for i in features:
    d[column] = i
    column+=1

In [39]:
vector.rename(d,axis=1,inplace=True)

In [40]:
vector

,aa,ability,able,absolute,absolutely,absurd,abuelita,abundance,abysmal,ac,...,yummy,yumy,yuzu,zack,zephyr,zero,zetton,zion,zov,zucchini
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.216849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2396,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0